# Generated by Django 4.0.4 on 2022-04-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='camara',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='diafragma',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='obturacion',
        ),
    ]
