# Generated by Django 4.0.4 on 2022-04-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_imagen_foto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='image',
            new_name='imagen',
        ),
    ]
